Shop/Cart/urls.py
from django.urls import path
from . import views
app_name = 'Cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('reduce/<int:product_id>/', views.cart_reduce, name='cart_reduce'),
    path('plus/<int:product_id>/', views.cart_plus, name='cart_plus'),
]

Shop/Orders/urls.py
from django.urls import path
from . import views
app_name = 'Orders'

urlpatterns = [
    path('', views.order_create, name='order_create'),
    
]

Shop/Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from Restora import views as Restora_views
from django.conf.urls.static import static
from Cart import views as Cart_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('Orders.urls',  namespace='orders')),
    path('cart/', include('Cart.urls',  namespace='cart')),   #включить до Restora, т.к. более ограничительным, чем последний.
    path('restora/', include('Restora.urls')),
    
]


urlpatterns += [
    path('', RedirectView.as_view(url='/restora/', permanent=True)),
]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/Cart/models.py
from django.db import models

# Create your models here.

Shop/Cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]

class CartAddProductForm(forms.Form):
    #TypedChoiceField с coerce=int для преобразования ввода в целое число
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='')    #количество между 1-20. 
    #update : позволяет указать, следует ли добавлять сумму к любому существующему значению в корзине для 
    # данного продукта (False) или если существующее значение должно быть обновлено с заданным значением (True).
    # HiddenInput, поскольку не требуется показывать это поле пользователю.
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

Shop/Cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from Restora.models import Dishes
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.

@require_POST   #разрешить только POST запросы, поскольку это представление изменит данные
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Dishes, id=product_id)
    print(f'prod = {product}')
    # извлекаем экземпляр продукта/блюда с заданным ID и проверяем CartAddProductForm.
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(dishe=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):   #получает id продукта 
    print("Product ID:", product_id) 
    cart = Cart(request)
    product = get_object_or_404(Dishes, id=product_id)   #извлекаем экземпляр продукта с заданным id и удаляем продукт из корзины
    print("Product:", product) 
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_reduce(request, product_id):
    quantity = request.GET.get('quantity')
    cart = Cart(request)
    product = get_object_or_404(Dishes, id=product_id)
    cart.reduce(product, int(quantity))
    return redirect('cart:cart_detail')
    
def cart_plus(request, product_id):
    quantity = request.GET.get('quantity')
    cart = Cart(request)
    product = get_object_or_404(Dishes, id=product_id)
    cart.plus(product, int(quantity))
    return redirect('cart:cart_detail')    
    
def cart_detail(request):
    cart = Cart(request)
    print(f'cart = {cart}')
    return render(request, 'cart/detail.html', {'cart': cart})

Shop/Cart/templates/cart/detail.html
{% extends 'base.html' %}
{% block title %}<TITLE>
    Ваш заказ - Restora</TITLE>
{% endblock %}
{% block content %}
{% load static %}
    <div class="block-cart">
    <h1 class="cart-text">Ваш заказ</h1>
    <table class="cart">
        <tbody>
        {% for item in cart %}  <!-- {'dish': <Dishes: Салат Цезарь>, 'price': Decimal('17.00'), 'quantity': 4, 'total_price': Decimal('68.00')}-->
            <tr class="cart-info">
                <td> <img src="{{ item.dish.image.url }}"></td> 
                <td><strong>{{ item.dish.name }}</strong></td>
                <td><a href="{% url 'cart:cart_reduce' item.dish.id %}?quantity={{ item.quantity }}"><svg class="card-icon" width="16" height="16" viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg" fill="white">
                   <g>
                       <path d="M22 11v2h-20v-2h20zm-22-2v6h24v-6h-24z"></path>
                   </g>
               </svg></a></td>
                <td><strong>{{ item.quantity }}</strong></td>
                <td><a href="{% url 'cart:cart_plus' item.dish.id %}?quantity={{ item.quantity }}"><svg class="card-icon" width="16" height="16" viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg" fill="white">
                   <g>
                       <path d="M13 2v9h9v2h-9v9h-2v-9h-9v-2h9v-9h2zm2-2h-6v9h-9v6h9v9h6v-9h9v-6h-9v-9z"></path>
                   </g>
               </svg></a></td>
                <td><a href="{% url "cart:cart_remove" item.dish.id %}"><svg class="card-icon" width="16" height="16" viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg" fill="white">
                   <g>
                       <path d="M20.197 2.837l.867.867-8.21 8.291 8.308 8.202-.866.867-8.292-8.21-8.23 8.311-.84-.84 8.213-8.32-8.312-8.231.84-.84 8.319 8.212 8.203-8.309zm-.009-2.837l-8.212 8.318-8.31-8.204-3.666 3.667 8.321 8.24-8.207 8.313 3.667 3.666 8.237-8.318 8.285 8.204 3.697-3.698-8.315-8.209 8.201-8.282-3.698-3.697z"></path>
                   </g>
               </svg></a></td> 
               
                <td class="num">{{ item.price }} BYN</td>
                <td class="num"><strong>{{ item.total_price }} BYN</strong></td>
            </tr>
        {% endfor %}   
        <tr class="total">
            <td>Всего к оплате</td>
            <td colspan="6"></td>
            <td class="num">{{ cart.get_total_price }} BYN</td>
        </tr>
        </tbody>
    </table>
        <div class="text-right">
        
            <h1><a href="{% url 'home' %}" class="button-light">Продолжить покупки</a></h1>
             
            <h1><a href="{% url "orders:order_create" %}" class="button">Оформить заказ</a></h1> 
                 
            
        </div>
    </div>
    
{% endblock %}    