Shop/Cart/urls.py
from django.urls import path
from . import views
app_name = 'Cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('reduce/<int:product_id>/', views.cart_reduce, name='cart_reduce'),
    path('plus/<int:product_id>/', views.cart_plus, name='cart_plus'),
]

Shop/Restora/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('home/', views.home, name= 'home'),
    path('home/salads', views.show_salads, name= 'salads'),
    path('home/cold_dishes', views.show_cold_dishes, name= 'cold_dishes'),
    path('home/hot_dishes', views.show_hot_dishes, name= 'hot_dishes'),
    path('home/side_dishes', views.show_side_dishes, name= 'side_dishes'),
    path('home/desserts', views.show_desserts, name= 'desserts'),
    path('home/drinkables', views.show_drinkables, name= 'drinkables'),
    path('home/about', views.about, name= 'about'),
    path('home/contacts', views.contacts, name= 'contacts'),
]

Shop/Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from Restora import views as Restora_views
from django.conf.urls.static import static
from Cart import views as Cart_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('Orders.urls',  namespace='orders')),
    path('cart/', include('Cart.urls',  namespace='cart')),   #включить до Restora, т.к. более ограничительным, чем последний.
    path('restora/', include('Restora.urls')),
    
]


urlpatterns += [
    path('', RedirectView.as_view(url='/restora/', permanent=True)),
]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/Restora/views.py
from django.shortcuts import render, redirect
from . import models
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import get_object_or_404
from Cart.forms import CartAddProductForm   #форма корзины
# Create your views here.


def home (request):
    return render(request, 'home.html', {'home':home})

def about (request):
    return render(request, 'about.html', {'about':about})

def contacts (request):
    return render(request, 'contacts.html', {'contacts':contacts})

def show_salads (request):
    viewed_salads = request.session.get('viewed_salads',[])
    salads = models.Dishes.objects.filter(category__name='Салаты')    #<QuerySet [<Dishes: Сельдь под шубой>, <Dishes: Овощной салат с семе>, <Dishes: Салат-микс с цыпленк>, <Dishes: Низуаз с тунцом>, <Dishes: Оливье>, <Dishes: Цезарь>]>
    paginator = Paginator(salads, 4)   #показ на стр. по 4 
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    #rows_count = (page_obj.paginator.count - 1) // 4 + 1  # Вычисляем количество рядов
    cart_product_form = CartAddProductForm()   #добавляем форму корзины
     # Получаем ингредиенты для каждого салата
    for salad in page_obj:
        ingredients = models.Ingredients.objects.filter(dishe_id=salad.id)
        salad.ingredients = []
        for ingredient in ingredients:
            product = models.Products.objects.get(id=ingredient.product_id)
            salad.ingredients.append(product.name)
     
    return render(request, 'salads.html', {'salads': salads, 
                                           'products': page_obj, 
                                           'viewed_salads':viewed_salads,
                                           'cart_product_form': cart_product_form,
                                           }) 

def show_cold_dishes (request):
    cold_dishes = models.Dishes.objects.filter(category__name='Холодные блюда')    #<QuerySet [<Dishes: Сельдь под шубой>, <Dishes: Овощной салат с семе>, <Dishes: Салат-микс с цыпленк>, <Dishes: Низуаз с тунцом>, <Dishes: Оливье>, <Dishes: Цезарь>]>
    paginator = Paginator(cold_dishes, 4)   #показ на стр. по 4 
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    #rows_count = (page_obj.paginator.count - 1) // 4 + 1  # Вычисляем количество рядов
    cart_product_form = CartAddProductForm()   #добавляем форму корзины
    for cold_dish in page_obj:
        ingredients = models.Ingredients.objects.filter(dishe_id=cold_dish.id)
        cold_dish.ingredients = []
        for ingredient in ingredients:
            product = models.Products.objects.get(id=ingredient.product_id)
            cold_dish.ingredients.append(product.name)
     
    return render(request, 'cold-dishes.html', {'cold_dishes': cold_dishes, 
                                           'products': page_obj, 
                                           'cart_product_form': cart_product_form,
                                           }) 

def show_hot_dishes (request):
    hot_dishes = models.Dishes.objects.filter(category__name='Горячие блюда')    #<QuerySet [<Dishes: Сельдь под шубой>, <Dishes: Овощной салат с семе>, <Dishes: Салат-микс с цыпленк>, <Dishes: Низуаз с тунцом>, <Dishes: Оливье>, <Dishes: Цезарь>]>
    paginator = Paginator(hot_dishes, 4)   #показ на стр. по 4 
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    cart_product_form = CartAddProductForm()   #добавляем форму корзины
    for hot_dish in page_obj:
        ingredients = models.Ingredients.objects.filter(dishe_id=hot_dish.id)
        hot_dish.ingredients = []
        for ingredient in ingredients:
            product = models.Products.objects.get(id=ingredient.product_id)
            hot_dish.ingredients.append(product.name)
     
    return render(request, 'hot-dishes.html', {'hot_dishes': hot_dishes, 
                                           'products': page_obj, 
                                           'cart_product_form': cart_product_form,
                                           }) 
    
def show_side_dishes (request):
    side_dishes = models.Dishes.objects.filter(category__name='Гарниры')    #<QuerySet [<Dishes: Сельдь под шубой>, <Dishes: Овощной салат с семе>, <Dishes: Салат-микс с цыпленк>, <Dishes: Низуаз с тунцом>, <Dishes: Оливье>, <Dishes: Цезарь>]>
    paginator = Paginator(side_dishes, 4)   #показ на стр. по 4 
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    cart_product_form = CartAddProductForm()   #добавляем форму корзины
    for side_dish in page_obj:
        ingredients = models.Ingredients.objects.filter(dishe_id=side_dish.id)
        side_dish.ingredients = []
        for ingredient in ingredients:
            product = models.Products.objects.get(id=ingredient.product_id)
            side_dish.ingredients.append(product.name)
     
    return render(request, 'side-dishes.html', {'side_dishes': side_dishes, 
                                           'products': page_obj, 
                                           'cart_product_form': cart_product_form,
                                           }) 
    
def show_desserts (request):
    desserts = models.Dishes.objects.filter(category__name='Десерты')    #<QuerySet [<Dishes: Сельдь под шубой>, <Dishes: Овощной салат с семе>, <Dishes: Салат-микс с цыпленк>, <Dishes: Низуаз с тунцом>, <Dishes: Оливье>, <Dishes: Цезарь>]>
    paginator = Paginator(desserts, 4)   #показ на стр. по 4 
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    cart_product_form = CartAddProductForm()   #добавляем форму корзины
    for dessert in page_obj:
        ingredients = models.Ingredients.objects.filter(dishe_id=dessert.id)
        dessert.ingredients = []
        for ingredient in ingredients:
            product = models.Products.objects.get(id=ingredient.product_id)
            dessert.ingredients.append(product.name)
     
    return render(request, 'desserts.html', {'desserts': desserts, 
                                           'products': page_obj, 
                                           'cart_product_form': cart_product_form,
                                           }) 
    
def show_drinkables (request):
    drinkables = models.Dishes.objects.filter(category__name='Напитки')    #<QuerySet [<Dishes: Сельдь под шубой>, <Dishes: Овощной салат с семе>, <Dishes: Салат-микс с цыпленк>, <Dishes: Низуаз с тунцом>, <Dishes: Оливье>, <Dishes: Цезарь>]>
    paginator = Paginator(drinkables, 4)   #показ на стр. по 4 
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    cart_product_form = CartAddProductForm()   #добавляем форму корзины
    for drinkable in page_obj:
        ingredients = models.Ingredients.objects.filter(dishe_id=drinkable.id)
        drinkable.ingredients = []
        for ingredient in ingredients:
            product = models.Products.objects.get(id=ingredient.product_id)
            drinkable.ingredients.append(product.name)
     
    return render(request, 'drinkables.html', {'drinkables': drinkables, 
                                           'products': page_obj, 
                                           'cart_product_form': cart_product_form,
                                           }) 

Shop/Restora/templates/base.html
{% load static %}

<!DOCTYPE html> 
<HTML> 
  <HEAD> 
    <meta charset="utf-8">
    <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
      <meta property="og:url" content="http://127.0.0.1:8000/catalog/home/">
      <meta property="og:title" content="Restora| Минск | Заказ еды из ресторана">
      <meta property="description"  content="Основу меню составляют позиции, приготовленные по рецептам Джейми Оливера">
      <meta property="og:type" content="website">
      <meta property="og:image" content="http://127.0.0.1:8000/static/Catalog/img/container.jpg">
      <link rel="canonical" href="http://127.0.0.1:8000/catalog/home/">
      {% comment %} <meta property="og:image:width" content="1200">
      <meta property="og:image:height" content="630">  {% endcomment %}
      {% comment %} <meta property="og:site_name" content="Заказ еды из ресторана | Минск | Restaurant"> {% endcomment %}
      <link rel="icon" href="{% static 'Restora/img/label.png' %}" type="image/jpg">
    
      {% block title %}<TITLE>Restora | Минск | Заказ еды из ресторана</TITLE>{% endblock %} 
      
      <style>    
    </style>
    <link rel="stylesheet" href="{% static 'Restora/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'Restora/css/flickity.css'%}" media="screen">
  </HEAD> 
  <BODY>  
    <div class="beginning">
        <div class="phone">
            <div class= "phone-text"><a href="tel:7989">7989</a></div>
            <div class="phone-logo">
                <a href="tel:7989"><img src ="{% static 'Restora/img/phone.jpg'%}"></a>
            </div>
        </div>
      
        <div class="acc-inf">
            <p>
                {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                <a href="{% url 'cart:cart_detail' %}"><u>
                    Количество: {{ total_items }};<br>
                    Сумма: {{ cart.get_total_price }} BYN</u>
                </a>
            {% else %}
                Корзина пуста.
            {% endif %}
        {% endwith %}
            </p>
            <div class="bag">
                <a href = "{% url 'cart:cart_detail' %}"><img src ="{% static 'Restora/img/cart.jpg'%}"></a>
            </div>
            <div class="login"> 
                <img src ="{% static 'Restora/img/login.jpg'%}">
            </div>
        </div>
    </div>
    <header>
        <div class="head">
            <div class="label">
                <div> 
                    <img src ="{% static 'Restora/img/label.png'%}">
                </div>
                <h1><a href = "{% url 'home' %}">Restora</a></h1>
            </div>
            <div class = "navi">
                <ul class ="menu">МЕНЮ
                   
                    <li ><a href = "{% url 'hot_dishes' %}">Горячие блюда </a></li>
                    <li ><a href = "{% url 'cold_dishes' %}">Холодные блюда</a></li>
                    <li ><a href = "{% url 'side_dishes' %}">Гарниры</a></li>
                    <li ><a href = "{% url 'salads' %}">Салаты</a></li> 
                    <li ><a href = "{% url 'drinkables' %}">Напитки</a></li>
                    <li ><a href = "{% url 'desserts' %}">Десерты</a></li>
                </ul>
                <ul>ДОСТАВКА</ul>
                <ul><a href = "{% url 'about' %}">О НАС</a></ul>
                <ul><a href = "{% url 'contacts' %}">КОНТАКТЫ</a></ul>
                
            </div>
        </div>
    </header>
 
    <div class ="container">
        {% block content %}
        {% endblock %}
    </div> 
   
    <footer>
        <div class="inf">
            <ul class="foot">КОМПАНИЯ
                <li><a href = "{% url 'home' %}">МЕНЮ</a></li>
                <li><a href = "{% url 'about' %}">О НАС</a></li>
                <li>ДОСТАВКА</li>
                
            </ul>
            <ul class="foot">УСЛУГИ
                <li>ВАКАНСИИ</li>
                <li>СТАЖИРОВКА</li>
              
            </ul>
            <ul class="foot"><a href = "{% url 'contacts' %}">КОНТАКТЫ 
                7989</a>
                <li>ЧАСТО ЗАДАВАЕМЫЕ ВОПРОСЫ</li>
                <li>РЕШЕНИЯ</li>
            </ul>
            <div class="foot-text"><a href ="https://t.me/SuperRestik_bot"> ТЕПЕРЬ МЫ ЕСТЬ<br>
                 В ТЕЛЕГРАМ
                
                <div class ="img-tel"> 
                    <svg class="card-icon" width="32" height="32" viewBox="0 0 24 24"
                        xmlns="http://www.w3.org/2000/svg" fill="white">
                       <g>
                           <path d="M12,0c-6.627,0 -12,5.373 -12,12c0,6.627 5.373,12 12,12c6.627,0 12,-5.373 12,-12c0,-6.627 -5.373,-12 -12,-12Zm0,2c5.514,0 10,4.486 10,10c0,5.514 -4.486,10 -10,10c-5.514,0 -10,-4.486 -10,-10c0,-5.514 4.486,-10 10,-10Zm2.692,14.889c0.161,0.115 0.368,0.143 0.553,0.073c0.185,-0.07 0.322,-0.228 0.362,-0.42c0.435,-2.042 1.489,-7.211 1.884,-9.068c0.03,-0.14 -0.019,-0.285 -0.129,-0.379c-0.11,-0.093 -0.263,-0.12 -0.399,-0.07c-2.096,0.776 -8.553,3.198 -11.192,4.175c-0.168,0.062 -0.277,0.223 -0.271,0.4c0.006,0.177 0.125,0.33 0.296,0.381c1.184,0.354 2.738,0.847 2.738,0.847c0,0 0.725,2.193 1.104,3.308c0.047,0.139 0.157,0.25 0.301,0.287c0.145,0.038 0.298,-0.001 0.406,-0.103c0.608,-0.574 1.548,-1.461 1.548,-1.461c0,0 1.786,1.309 2.799,2.03Zm-5.505,-4.338l0.84,2.769l0.186,-1.754c0,0 3.243,-2.925 5.092,-4.593c0.055,-0.048 0.062,-0.13 0.017,-0.188c-0.045,-0.057 -0.126,-0.071 -0.188,-0.032c-2.143,1.368 -5.947,3.798 -5.947,3.798Z"></path>
                       </g>
                   </svg>
                </a>
                </div>
            </div>
        </div>
        <div class="legend">
            <p>RESTAURANT @ 2023 PRIVACY POLICY</p>
            <p>EMAIL NEWSLETTER SIGNUP  </p>
        </div>
    </footer>
<!--Подключаю слайдер-->
<script src="{% static 'Restora/js/flickity.pkgd.js' %}"></script>
<script>
    var flkty = new Flickity('.main-gallery', {
        // options
        cellAlign: 'left',
        contain: true,
        autoPlay: 3000,
        selectedAttraction: 0.01,
        friction: 0.15,
        pauseAutoPlayOnHover: false
    });
</script>


</BODY> 
</HTML> 

Shop/Restora/templates/catalog.html
{% extends 'base.html' %}
{% block title %}<TITLE>Catalog</TITLE>{% endblock %} 
{% block content %}   
{% load static %}


{% endblock %}   

Shop/Restora/templates/cold-dishes.html
{% extends 'base.html' %}

{% block content %}   
{% load static %}

<div class="products-container">
    {% for cold_dish in products %}
        {% if forloop.counter0|divisibleby:2 %}
            <div class="row">
        {% endif %}
       
        <div class="product-card">
            <ul>
                <li><a href="javascript:PopUpShow('popup{{ forloop.counter }}')">     <!--при нажатии на изображение открывается popup карточка-->
                    {% if cold_dish.image %}
                        <img class="product-image" src="{{ cold_dish.image.url }}">
                    {% else %}
                        <p>No image</p>
                    {% endif %}
                    </a>
                </li>
                <li>
                    <p class ="product-name">{{cold_dish.name}}</p>
                </li>
                <li>
                    <p class ="product-description"> 
                        {% for ingredient in cold_dish.ingredients %}
                          {{ ingredient }}{% if not forloop.last %},{% endif %}    <!--переменную forloop.last -булевое значение True для последнего элемента в цикле for. -->
                        {% endfor %}.
                     </p>
                </li>
                <li class="in-bag"><p class="product-price" >{{cold_dish.price}} BYN</p>
                    
                    <form action="{% url "cart:cart_add" cold_dish.id %}" method="post">
                        {{ cart_product_form }}
                        {% csrf_token %}
                        <input class="button-in-bag" type="submit" value="В корзину">    <!--onclick="yaCounter94548736.reachGoal('add_cart'); return true;-->
                    </form>
                </li>
        </ul>

    </div>
    <div class="product-card-popup" id="popup{{ forloop.counter }}">    <!--{{ forloop.counter }}-идентификаторы id для попапов и функций PopUpShow() и PopUpHide(). Это обеспечит уникальность идентификаторов и связанных функций для каждого попапа-->
        <div class="b-popup-content">
        <a href="javascript:PopUpHide('popup{{ forloop.counter }}')">❌</a>
        <ul>
            <li>
                {% if cold_dish.image %}
                    <img class="product-image" src="{{ cold_dish.image.url }}">
                {% else %}
                    <p>No image</p>
                {% endif %}
               
            </li>
            <li>
                <p class ="product-name">{{cold_dish.name}}</p>
            </li>
            <li>
                <p class ="product-description"> 
                    {% for ingredient in cold_dish.ingredients %}
                      {{ ingredient }}{% if not forloop.last %},{% endif %}    <!--переменную forloop.last -булевое значение True для последнего элемента в цикле for. -->
                    {% endfor %}.
                 </p>
            </li>
            <li class="in-bag"><p class="product-price" >{{cold_dish.price}} BYN</p>
                <form action="{% url "cart:cart_add" cold_dish.id %}" method="post">
                    {{ cart_product_form }} 
                    {% csrf_token %}
                    <input class="button-in-bag" type="submit" value="В корзину">    <!--onclick="yaCounter94548736.reachGoal('add_cart'); return true;-->
                </form>
            </li>
    </ul>
    
    </div>
</div>
        {% if forloop.counter0|add:1|divisibleby:2 or forloop.last %}
    </div>
            {% if not forloop.last %}
                <hr>
            {% endif %}
        {% endif %}
    {% endfor %}
 </div> 

{% include 'pagination.html' %}   <!-- Это способ “включить” один шаблон в другой.-->

<!--подключение popup card-->
<script src="http://code.jquery.com/jquery-2.0.2.min.js"></script>
<script>
    $(document).ready(function(){
        // Скрыть PopUp при загрузке страницы    
        {% for salad in products %}
        PopUpHide('popup{{ forloop.counter }}');
        {% endfor %}
        
    });
    //Функция отображения PopUp
    function PopUpShow(popupId){
        $("#" + popupId).show();
    }
    //Функция скрытия PopUp
    function PopUpHide(popupId){
        $("#" + popupId).hide();
    }
</script>

{% endblock %}   

Shop/Restora/templates/desserts.html
{% extends 'base.html' %}

{% block content %}   
{% load static %}

<div class="products-container">
    {% for dessert in products %}
        {% if forloop.counter0|divisibleby:2 %}
            <div class="row">
        {% endif %}
       
        <div class="product-card">
            <ul>
                <li><a href="javascript:PopUpShow('popup{{ forloop.counter }}')">     <!--при нажатии на изображение открывается popup карточка-->
                    {% if dessert.image %}
                        <img class="product-image" src="{{ dessert.image.url }}">
                    {% else %}
                        <p>No image</p>
                    {% endif %}
                    </a>
                </li>
                <li>
                    <p class ="product-name">{{dessert.name}}</p>
                </li>
                <li>
                    <p class ="product-description"> 
                        {% for ingredient in dessert.ingredients %}
                          {{ ingredient }}{% if not forloop.last %},{% endif %}    <!--переменную forloop.last -булевое значение True для последнего элемента в цикле for. -->
                        {% endfor %}.
                     </p>
                </li>
                <li class="in-bag"><p class="product-price" >{{dessert.price}} BYN</p>
                    
                    <form action="{% url "cart:cart_add" dessert.id %}" method="post">
                        {{ cart_product_form }}
                        {% csrf_token %}
                        <input class="button-in-bag" type="submit" value="В корзину">    <!--onclick="yaCounter94548736.reachGoal('add_cart'); return true;-->
                    </form>
                </li>
        </ul>

    </div>
    <div class="product-card-popup" id="popup{{ forloop.counter }}">    <!--{{ forloop.counter }}-идентификаторы id для попапов и функций PopUpShow() и PopUpHide(). Это обеспечит уникальность идентификаторов и связанных функций для каждого попапа-->
        <div class="b-popup-content">
        <a href="javascript:PopUpHide('popup{{ forloop.counter }}')">❌</a>
        <ul>
            <li>
                {% if dessert.image %}
                    <img class="product-image" src="{{ dessert.image.url }}">
                {% else %}
                    <p>No image</p>
                {% endif %}
               
            </li>
            <li>
                <p class ="product-name">{{dessert.name}}</p>
            </li>
            <li>
                <p class ="product-description"> 
                    {% for ingredient in dessert.ingredients %}
                      {{ ingredient }}{% if not forloop.last %},{% endif %}    <!--переменную forloop.last -булевое значение True для последнего элемента в цикле for. -->
                    {% endfor %}.
                 </p>
            </li>
            <li class="in-bag"><p class="product-price" >{{dessert.price}} BYN</p>
                <form action="{% url "cart:cart_add" dessert.id %}" method="post">
                    {{ cart_product_form }} 
                    {% csrf_token %}
                    <input class="button-in-bag" type="submit" value="В корзину">    <!--onclick="yaCounter94548736.reachGoal('add_cart'); return true;-->
                </form>
            </li>
    </ul>
    
    </div>
</div>
        {% if forloop.counter0|add:1|divisibleby:2 or forloop.last %}
    </div>
            {% if not forloop.last %}
                <hr>
            {% endif %}
        {% endif %}
    {% endfor %}
 </div> 

{% include 'pagination.html' %}   <!-- Это способ “включить” один шаблон в другой.-->

<!--подключение popup card-->
<script src="http://code.jquery.com/jquery-2.0.2.min.js"></script>
<script>
    $(document).ready(function(){
        // Скрыть PopUp при загрузке страницы    
        {% for salad in products %}
        PopUpHide('popup{{ forloop.counter }}');
        {% endfor %}
        
    });
    //Функция отображения PopUp
    function PopUpShow(popupId){
        $("#" + popupId).show();
    }
    //Функция скрытия PopUp
    function PopUpHide(popupId){
        $("#" + popupId).hide();
    }
</script>

{% endblock %}   

Shop/Restora/templates/drinkables.html
{% extends 'base.html' %}

{% block content %}   
{% load static %}

<div class="products-container">
    {% for drinkable in products %}
        {% if forloop.counter0|divisibleby:2 %}
            <div class="row">
        {% endif %}
       
        <div class="product-card">
            <ul>
                <li><a href="javascript:PopUpShow('popup{{ forloop.counter }}')">     <!--при нажатии на изображение открывается popup карточка-->
                    {% if drinkable.image %}
                        <img class="product-image" src="{{ drinkable.image.url }}">
                    {% else %}
                        <p>No image</p>
                    {% endif %}
                    </a>
                </li>
                <li>
                    <p class ="product-name">{{drinkable.name}}</p>
                </li>
                <li>
                    <p class ="product-description"> 
                        {% for ingredient in drinkable.ingredients %}
                          {{ ingredient }}{% if not forloop.last %},{% endif %}    <!--переменную forloop.last -булевое значение True для последнего элемента в цикле for. -->
                        {% endfor %}.
                     </p>
                </li>
                <li class="in-bag"><p class="product-price" >{{drinkable.price}} BYN</p>
                    
                    <form action="{% url "cart:cart_add" drinkable.id %}" method="post">
                        {{ cart_product_form }}
                        {% csrf_token %}
                        <input class="button-in-bag" type="submit" value="В корзину">    <!--onclick="yaCounter94548736.reachGoal('add_cart'); return true;-->
                    </form>
                </li>
        </ul>

    </div>
    <div class="product-card-popup" id="popup{{ forloop.counter }}">    <!--{{ forloop.counter }}-идентификаторы id для попапов и функций PopUpShow() и PopUpHide(). Это обеспечит уникальность идентификаторов и связанных функций для каждого попапа-->
        <div class="b-popup-content">
        <a href="javascript:PopUpHide('popup{{ forloop.counter }}')">❌</a>
        <ul>
            <li>
                {% if drinkable.image %}
                    <img class="product-image" src="{{ drinkable.image.url }}">
                {% else %}
                    <p>No image</p>
                {% endif %}
               
            </li>
            <li>
                <p class ="product-name">{{drinkable.name}}</p>
            </li>
            <li>
                <p class ="product-description"> 
                    {% for ingredient in drinkable.ingredients %}
                      {{ ingredient }}{% if not forloop.last %},{% endif %}    <!--переменную forloop.last -булевое значение True для последнего элемента в цикле for. -->
                    {% endfor %}.
                 </p>
            </li>
            <li class="in-bag"><p class="product-price" >{{drinkable.price}} BYN</p>
                <form action="{% url "cart:cart_add" drinkable.id %}" method="post">
                    {{ cart_product_form }} 
                    {% csrf_token %}
                    <input class="button-in-bag" type="submit" value="В корзину">    <!--onclick="yaCounter94548736.reachGoal('add_cart'); return true;-->
                </form>
            </li>
    </ul>
    
    </div>
</div>
        {% if forloop.counter0|add:1|divisibleby:2 or forloop.last %}
    </div>
            {% if not forloop.last %}
                <hr>
            {% endif %}
        {% endif %}
    {% endfor %}
 </div> 

{% include 'pagination.html' %}   <!-- Это способ “включить” один шаблон в другой.-->

<!--подключение popup card-->
<script src="http://code.jquery.com/jquery-2.0.2.min.js"></script>
<script>
    $(document).ready(function(){
        // Скрыть PopUp при загрузке страницы    
        {% for salad in products %}
        PopUpHide('popup{{ forloop.counter }}');
        {% endfor %}
        
    });
    //Функция отображения PopUp
    function PopUpShow(popupId){
        $("#" + popupId).show();
    }
    //Функция скрытия PopUp
    function PopUpHide(popupId){
        $("#" + popupId).hide();
    }
</script>

{% endblock %}   